# IBM Risk Atlas x AIUC-1 Crosswalk

## About this notebook

This notebook contains three sections. 
1. Overview of AIUC-1 resources in the AI Atlas Nexus repository.
2. Using the AIAtlasNexus library API to load the data.
3. A crosswalk pandas dataframe showing linkages between AIUC-1 Framework requirements and IBM AI Risk Atlas risks.

In [1]:
# imports
import pandas as pd

from collections import defaultdict
from rich import print
from pathlib import Path

from ai_atlas_nexus import AIAtlasNexus

/Users/ingevejs/Documents/workspace/ingelise/risk-atlas-nexus/v-ai-atlas-nexus/lib/python3.11/site-packages/requests/__init__.py:113: RequestsDependencyWarning: urllib3 (2.6.3) or chardet (6.0.0.post1)/charset_normalizer (3.4.4) doesn't match a supported version!
  warnings.warn(
/Users/ingevejs/Documents/workspace/ingelise/risk-atlas-nexus/src/ai_atlas_nexus/toolkit/job_utils.py:4: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from tqdm.autonotebook import tqdm

## 1. Overview of AIUC-1 resources

### Hierarchy Structure

- **6 Principles** (A-F)
  - Contains 51 Requirements (Rules)
    - Each Requirement contains 1-3 Control Activities (Rules)
      - Total: 129 Control Activities

### Class Details

#### Core Classes

| Class           | Purpose                                                             | Count |
| --------------- | ------------------------------------------------------------------- | ----- |
| Principle       | Top-level AIUC-1 framework principle                                | 6     |
| Requirement     | Specific requirement associated with a principle                    | 51    |
| ControlActivity | Concrete control (Permission/Prohibition/Obligation/Recommendation) | 129   |

## 2. Load the data

In [2]:
ran = AIAtlasNexus() # default configuration 

# We can use any of the classes as the class_name argument with "get_all", let's choose `certification` to start
aiuc1_certs = ran.get_all(class_name="certification", taxonomy="aiuc1")
aiuc1_principles = ran.get_all(class_name="principle", taxonomy="aiuc1")
aiuc1_requirements = ran.get_all(class_name="requirement", taxonomy="aiuc1")

print(f"\n# Total AIUC certificates available : {len(aiuc1_certs)}") # 1
print(f"\n# Total AIUC principles available : {len(aiuc1_principles)}") # 6
print(f"\n# Total AIUC requirements available : {len(aiuc1_requirements)}") # 51

# Let's just print out a few for now
print(f"\n# First 2 AIUC principles in list ") 
print(aiuc1_principles[:2])

# Find an element by ID
instance = ran.get_by_id(
    class_name="principle", 
    identifier="aiuc1-principle-d"
)
print(f"\n# Get instance of principle, `aiuc1-principle-d` by ID ") 
print(instance)

[2026-02-26 10:49:27:79] - INFO - AIAtlasNexus - Created AIAtlasNexus instance. Base_dir: None

# Total AIUC certificates available : 1

# Total AIUC principles available : 6

# Total AIUC requirements available : 51

# First 2 AIUC principles in list

[
    Principle(
        id='aiuc1-principle-a',
        name='Principle A: Data and Privacy',
        description='Protect against data leakage, IP leakage, and training on user data without consent',
        url=None,
        dateCreated=None,
        dateModified=None,
        exact_mappings=[],
        close_mappings=[],
        related_mappings=[],
        narrow_mappings=[],
        broad_mappings=[],
        isDefinedByTaxonomy='aiuc1',
        isDefinedByVocabulary=None,
        hasDocumentation=['AIUC-1-Jan-2026'],
        isPartOf=None,
        requiredByTask=[],
        requiresCapability=[],
        implementedByAdapter=[],
        type='Principle'
    ),
    Principle(
        id='aiuc1-principle-b',
        name='Principle B: Security',
        description='Protect against adversarial attacks like jailbreaks and prompt injections as well as
unauthorized tool calls',
        url=None,
        dateCreated=None,
        dateModified=None,
        exact_mappings=[],
        close_mappings=[],
        related_mappings=[],
        narrow_mappings=[],
        broad_mappings=[],
        isDefinedByTaxonomy='aiuc1',
        isDefinedByVocabulary=None,
        hasDocumentation=['AIUC-1-Jan-2026'],
        isPartOf=None,
        requiredByTask=[],
        requiresCapability=[],
        implementedByAdapter=[],
        type='Principle'
    )
]

# Get instance of principle, `aiuc1-principle-d` by ID

Principle(
    id='aiuc1-principle-d',
    name='Principle D: Reliability',
    description='Prevent hallucinations and unreliable tool calls to business systems',
    url=None,
    dateCreated=None,
    dateModified=None,
    exact_mappings=[],
    close_mappings=[],
    related_mappings=[],
    narrow_mappings=[],
    broad_mappings=[],
    isDefinedByTaxonomy='aiuc1',
    isDefinedByVocabulary=None,
    hasDocumentation=['AIUC-1-Jan-2026'],
    isPartOf=None,
    requiredByTask=[],
    requiresCapability=[],
    implementedByAdapter=[],
    type='Principle'
)

### 2.1. Associated requirements 
We can get all the associated requirements for a given principle:

In [3]:
# Find an element by attribute value pair
instances = ran.query(
    class_name="requirement", 
    hasPrinciple="aiuc1-principle-d"
)

print(f"\n# Get a list of of requirements, that are part of `aiuc1-principle-d` principle") 
print(instances)

# Get a list of of requirements, that are part of `aiuc1-principle-d` principle

[
    Requirement(
        id='aiuc1-req-d001',
        name='Prevent hallucinated outputs',
        description='Implement safeguards or technical controls to prevent hallucinated outputs',
        url=None,
        dateCreated=None,
        dateModified=None,
        exact_mappings=[],
        close_mappings=['atlas-hallucination'],
        related_mappings=[
            'atlas-incomplete-advice',
            'atlas-unreliable-source-attribution',
            'llm092025-misinformation',
            'atlas-poor-model-accuracy',
            'llm052025-improper-output-handling',
            'atlas-untraceable-attribution'
        ],
        narrow_mappings=[],
        broad_mappings=[],
        isDefinedByTaxonomy='aiuc1',
        hasRule=['aiuc1-ctrl-d001-1', 'aiuc1-ctrl-d001-2', 'aiuc1-ctrl-d001-3'],
        type='Requirement',
        hasApplication=['MANDATORY'],
        hasFrequency='MONTHS_12',
        hasKeywords=[],
        hasPrinciple=['aiuc1-principle-d'],
        appliesToCapability=[],
        hasRequirementType=None
    ),
    Requirement(
        id='aiuc1-req-d002',
        name='Third-party testing for hallucinations',
        description='Appoint expert third-parties to evaluate hallucinated outputs at least every 3 months',
        url=None,
        dateCreated=None,
        dateModified=None,
        exact_mappings=[],
        close_mappings=['atlas-hallucination'],
        related_mappings=['atlas-poor-model-accuracy', 'llm092025-misinformation'],
        narrow_mappings=[],
        broad_mappings=[],
        isDefinedByTaxonomy='aiuc1',
        hasRule=['aiuc1-ctrl-d002-1'],
        type='Requirement',
        hasApplication=['MANDATORY'],
        hasFrequency='MONTHS_3',
        hasKeywords=[],
        hasPrinciple=['aiuc1-principle-d'],
        appliesToCapability=[],
        hasRequirementType=None
    ),
    Requirement(
        id='aiuc1-req-d003',
        name='Restrict unsafe tool calls',
        description='Implement safeguards or technical controls to prevent tool calls in AI systems from executing
unauthorized actions, accessing restricted information, or making decisions beyond their intended scope',
        url=None,
        dateCreated=None,
        dateModified=None,
        exact_mappings=[],
        close_mappings=['atlas-misaligned-actions-agentic', 'atlas-function-calling-hallucination-agentic'],
        related_mappings=[
            'llm082025-vector-and-embedding-weaknesses',
            'atlas-redundant-actions-agentic',
            'llm062025-excessive-agency',
            'atlas-unauthorized-use-agentic',
            'atlas-function-calling-hallucination-agentic',
            'llm102025-unbounded-consumption',
            'atlas-external-resources-attack-agentic'
        ],
        narrow_mappings=[],
        broad_mappings=[],
        isDefinedByTaxonomy='aiuc1',
        hasRule=[
            'aiuc1-ctrl-d003-1',
            'aiuc1-ctrl-d003-2',
            'aiuc1-ctrl-d003-3',
            'aiuc1-ctrl-d003-4',
            'aiuc1-ctrl-d003-5'
        ],
        type='Requirement',
        hasApplication=['MANDATORY'],
        hasFrequency='MONTHS_12',
        hasKeywords=[],
        hasPrinciple=['aiuc1-principle-d'],
        appliesToCapability=[],
        hasRequirementType=None
    ),
    Requirement(
        id='aiuc1-req-d004',
        name='Third-party testing of tool calls',
        description='Appoint expert third-parties to evaluate tool calls in AI systems, including executing
unauthorized actions, accessing restricted information, or making decisions beyond their intended scope at least
every 3 months',
        url=None,
        dateCreated=None,
        dateModified=None,
        exact_mappings=[],
        close_mappings=['atlas-function-calling-hallucination-agentic'],
        related_mappings=[
            'atlas-function-calling-hallucination-agentic',
            'atlas-incomplete-ai-agent-evaluation-agentic',
            'llm062025-excessive-agency',
            'atlas-misaligned-actions-agentic'
        ],
        narrow_mappings=[],
        broad_mappings=[],
        isDefinedByTaxonomy='aiuc1',
        hasRule=['aiuc1-ctrl-d004-1'],
        type='Requirement',
        hasApplication=['MANDATORY'],
        hasFrequency='MONTHS_3',
        hasKeywords=[],
        hasPrinciple=['aiuc1-principle-d'],
        appliesToCapability=[],
        hasRequirementType=None
    )
]

In [4]:
# all rules associated with Principle D
principle_d_rules =  [req.hasRule for req in instances]
principle_d_rules_flat = [x for xs in principle_d_rules for x in xs]
full_rule_list = [ran.get_by_id(class_name="rules", identifier=id) for id in principle_d_rules_flat]
print(full_rule_list)

[
    ControlActivityObligation(
        id='aiuc1-ctrl-d001-1',
        name='D001.1 Config: Groundedness filter',
        description='Implementing factual accuracy controls. For example, deploying available fact-checking
mechanisms, flagging uncertain or low-confidence responses.',
        url=None,
        dateCreated=None,
        dateModified=None,
        exact_mappings=[],
        close_mappings=[],
        related_mappings=[],
        narrow_mappings=[],
        broad_mappings=[],
        isDefinedByTaxonomy='aiuc1',
        hasRule=[],
        type='ControlActivityObligation',
        hasControlApplication='CORE',
        hasEvidenceCategory=['TECHNICAL_IMPLEMENTATION'],
        hasTypicalLocation=['Engineering Code'],
        appliesToCapability=[],
        hasRequirement='aiuc1-req-d001',
        hasRequirementType=None,
        hasTypicalEvidence='Screenshot of code or configuration showing groundedness validation - may include
filters checking responses against source documents, fact-checking API integration, or logic comparing generated
content to retrieved context for factual accuracy.'
    ),
    ControlActivityObligation(
        id='aiuc1-ctrl-d001-2',
        name='D001.2 Demonstration: User-facing citations & source attributions',
        description='Establishing information source validation. For example, requiring citations for factual
claims, implementing source reliability checks.',
        url=None,
        dateCreated=None,
        dateModified=None,
        exact_mappings=[],
        close_mappings=[],
        related_mappings=[],
        narrow_mappings=[],
        broad_mappings=[],
        isDefinedByTaxonomy='aiuc1',
        hasRule=[],
        type='ControlActivityObligation',
        hasControlApplication='CORE',
        hasEvidenceCategory=['TECHNICAL_IMPLEMENTATION'],
        hasTypicalLocation=['Product'],
        appliesToCapability=[],
        hasRequirement='aiuc1-req-d001',
        hasRequirementType=None,
        hasTypicalEvidence='Screenshot of UI or output format showing citations and source attributions provided to
users - may include inline citations, source links, reference lists, or attribution labels identifying where
information originated.'
    ),
    ControlActivityRecommendation(
        id='aiuc1-ctrl-d001-3',
        name='D001.3 Demonstration: User-facing uncertainty labels',
        description='Maintaining uncertainty communication. For example, displaying confidence levels, providing
appropriate disclaimers for generated information.',
        url=None,
        dateCreated=None,
        dateModified=None,
        exact_mappings=[],
        close_mappings=[],
        related_mappings=[],
        narrow_mappings=[],
        broad_mappings=[],
        isDefinedByTaxonomy='aiuc1',
        hasRule=[],
        type='ControlActivityRecommendation',
        hasControlApplication='SUPPLEMENTAL',
        hasEvidenceCategory=['TECHNICAL_IMPLEMENTATION'],
        hasTypicalLocation=['Product'],
        appliesToCapability=[],
        hasRequirement='aiuc1-req-d001',
        hasRequirementType=None,
        hasTypicalEvidence='Screenshot of UI or output format showing confidence levels, uncertainty disclaimers,
or warnings for generated information - may include confidence score displays, low-certainty warnings, or standard
disclaimers about potential inaccuracies.'
    ),
    ControlActivityObligation(
        id='aiuc1-ctrl-d002-1',
        name='D002.1 Report: Hallucination testing results',
        description='Appointing qualified third-party assessors. Including selecting assessors with relevant
technical capabilities for identified risk areas, maintaining records of assessor qualifications and
independence.\n- Conducting regular testing. Including defining testing scope and methodologies based on risk
taxonomy and performing assessments at least every quarter.\n- Maintaining documentation. Including testing scope,
results, and remediation actions taken, tracking follow-up activities and resolution timelines.',
        url=None,
        dateCreated=None,
        dateModified=None,
        exact_mappings=[],
        close_mappings=[],
        related_mappings=[],
        narrow_mappings=[],
        broad_mappings=[],
        isDefinedByTaxonomy='aiuc1',
        hasRule=[],
        type='ControlActivityObligation',
        hasControlApplication='CORE',
        hasEvidenceCategory=['THIRD_PARTY_EVALS'],
        hasTypicalLocation=['Third-party evaluation report'],
        appliesToCapability=[],
        hasRequirement='aiuc1-req-d002',
        hasRequirementType=None,
        hasTypicalEvidence='Third-party evaluation report showing hallucination testing - must include risk
taxonomy tested, testing methodology and findings, and improvement tracking with remediation timelines and
documentation.'
    ),
    ControlActivityObligation(
        id='aiuc1-ctrl-d003-1',
        name='D003.1 Config: Tool authorization & validation',
        description='Implementing function call validation and authorization. For example, restricting tool access
to approved functions, validating parameters before execution.',
        url=None,
        dateCreated=None,
        dateModified=None,
        exact_mappings=[],
        close_mappings=[],
        related_mappings=[],
        narrow_mappings=[],
        broad_mappings=[],
        isDefinedByTaxonomy='aiuc1',
        hasRule=[],
        type='ControlActivityObligation',
        hasControlApplication='CORE',
        hasEvidenceCategory=['TECHNICAL_IMPLEMENTATION'],
        hasTypicalLocation=['Engineering Code'],
        appliesToCapability=[],
        hasRequirement='aiuc1-req-d003',
        hasRequirementType=None,
        hasTypicalEvidence='Screenshot of code or configuration showing function allowlists, parameter validation
logic, or authz checks before tool execution - may include tool permission schemas, input validation functions, or
access control lists restricting available tools per agent/user.'
    ),
    ControlActivityObligation(
        id='aiuc1-ctrl-d003-2',
        name='D003.2 Config: Rate limits for tools',
        description='Enforcing rate limits and transaction caps for autonomous tool use.',
        url=None,
        dateCreated=None,
        dateModified=None,
        exact_mappings=[],
        close_mappings=[],
        related_mappings=[],
        narrow_mappings=[],
        broad_mappings=[],
        isDefinedByTaxonomy='aiuc1',
        hasRule=[],
        type='ControlActivityObligation',
        hasControlApplication='CORE',
        hasEvidenceCategory=['TECHNICAL_IMPLEMENTATION'],
        hasTypicalLocation=['Engineering Code'],
        appliesToCapability=[],
        hasRequirement='aiuc1-req-d003',
        hasRequirementType=None,
        hasTypicalEvidence='Screenshot of code or configuration showing rate limits and transaction caps on tool
usage - may include per-tool usage quotas, time-windowed limits, or circuit breakers preventing excessive
autonomous tool calls.'
    ),
    ControlActivityObligation(
        id='aiuc1-ctrl-d003-3',
        name='D003.3 Config: Tool call log',
        description='Establishing execution monitoring and logging. For example, tracking all tool calls,
monitoring for unauthorized access attempts or scope violations.',
        url=None,
        dateCreated=None,
        dateModified=None,
        exact_mappings=[],
        close_mappings=[],
        related_mappings=[],
        narrow_mappings=[],
        broad_mappings=[],
        isDefinedByTaxonomy='aiuc1',
        hasRule=[],
        type='ControlActivityObligation',
        hasControlApplication='CORE',
        hasEvidenceCategory=['TECHNICAL_IMPLEMENTATION'],
        hasTypicalLocation=['Logs'],
        appliesToCapability=[],
        hasRequirement='aiuc1-req-d003',
        hasRequirementType=None,
        hasTypicalEvidence='Screenshot of logging configuration, monitoring dashboard, or audit logs showing
tracked tool calls - may include tool execution logs with timestamps and parameters, alerts for unauthorized access
attempts, or monitoring system flagging scope violations.'
    ),
    ControlActivityRecommendation(
        id='aiuc1-ctrl-d003-4',
        name='D003.4 Config: Human-approval workflows',
        description='Requiring human approval for sensitive tool operations. For example, requiring human
confirmation before executing high-risk actions, implementing approval workflows for operations beyond autonomous
boundaries.',
        url=None,
        dateCreated=None,
        dateModified=None,
        exact_mappings=[],
        close_mappings=[],
        related_mappings=[],
        narrow_mappings=[],
        broad_mappings=[],
        isDefinedByTaxonomy='aiuc1',
        hasRule=[],
        type='ControlActivityRecommendation',
        hasControlApplication='SUPPLEMENTAL',
        hasEvidenceCategory=['OPERATIONAL_PRACTICES'],
        hasTypicalLocation=['Internal processes'],
        appliesToCapability=[],
        hasRequirement='aiuc1-req-d003',
        hasRequirementType=None,
        hasTypicalEvidence='Screenshot of approval workflow, code requiring human confirmation, or ticketing system
for sensitive tool operations'
    ),
    ControlActivityRecommendation(
        id='aiuc1-ctrl-d003-5',
        name='D003.5 Documentation: tool call log reviews',
        description='Reviewing patterns of AI tool usage. For example, identifying anomalies, updating tool
permissions, and retiring unused or high-risk functions during scheduled evaluations.',
        url=None,
        dateCreated=None,
        dateModified=None,
        exact_mappings=[],
        close_mappings=[],
        related_mappings=[],
        narrow_mappings=[],
        broad_mappings=[],
        isDefinedByTaxonomy='aiuc1',
        hasRule=[],
        type='ControlActivityRecommendation',
        hasControlApplication='SUPPLEMENTAL',
        hasEvidenceCategory=['OPERATIONAL_PRACTICES'],
        hasTypicalLocation=['Internal processes'],
        appliesToCapability=[],
        hasRequirement='aiuc1-req-d003',
        hasRequirementType=None,
        hasTypicalEvidence='Reports or documentation showing periodic review of tool usage patterns, permission
updates, and function retirement decisions - may include usage analytics identifying anomalies, change logs showing
permission adjustments, or records of deprecated/retired tools with rationale.'
    ),
    ControlActivityObligation(
        id='aiuc1-ctrl-d004-1',
        name='D004.1 Report: Tool call testing',
        description='Appointing qualified third-party assessors. Including selecting assessors with relevant
technical capabilities for identified risk areas, maintaining records of assessor qualifications and
independence.\n- Conducting regular testing. Including defining testing scope and methodologies based on risk
taxonomy and performing assessments of tool calls at least every quarter.\n- Maintaining documentation. Including
testing scope, results, and remediation actions taken, tracking follow-up activities and resolution timelines.',
        url=None,
        dateCreated=None,
        dateModified=None,
        exact_mappings=[],
        close_mappings=[],
        related_mappings=[],
        narrow_mappings=[],
        broad_mappings=[],
        isDefinedByTaxonomy='aiuc1',
        hasRule=[],
        type='ControlActivityObligation',
        hasControlApplication='CORE',
        hasEvidenceCategory=['THIRD_PARTY_EVALS'],
        hasTypicalLocation=['Third-party evaluation report'],
        appliesToCapability=[],
        hasRequirement='aiuc1-req-d004',
        hasRequirementType=None,
        hasTypicalEvidence='Third-party evaluation report showing tool call testing - must include risk taxonomy
tested, testing methodology and findings, and improvement tracking with remediation timelines and documentation.'
    )
]

## 3. AIUC-1 × IBM AI Risk Atlas
Let's automatically create a crosswalk from the mappings provided.

### 3.1 IBM AI Risk Atlas crosswalks by risk

In [5]:
# Util functions

def get_mapped_aiuc1_requirements(ibm_risk_id, aiuc1_requirements):
    """
    Find the AIUC-1 requirements that map to a given IBM risk
    """
    mapping_fields = ['close_mappings', 'exact_mappings', 'related_mappings', 'broad_mappings', 'narrow_mappings']
    matched_reqs = defaultdict(list)  # req_id -> [mapping_types]
    
    for req in aiuc1_requirements:
        for field_name in mapping_fields:
            if hasattr(req, field_name):
                field_value = getattr(req, field_name)
                if field_value:
                    ids = field_value if isinstance(field_value, list) else [field_value]
                    if ibm_risk_id in ids:
                        if req.id not in matched_reqs:
                            matched_reqs[req.id] = []
                        matched_reqs[req.id].append(field_name.replace('_mappings', '').capitalize())
    
    return matched_reqs

# Get all AIUC-1 requirements
aiuc1_requirements = ran.get_all(class_name='requirement', taxonomy='aiuc1')

# Get all IBM Risk Atlas risks
ibm_risks = ran.get_all(class_name='entries', taxonomy='ibm-risk-atlas')
ibm_risks = [r for r in ibm_risks if hasattr(r, 'isDefinedByTaxonomy') and r.isDefinedByTaxonomy == 'ibm-risk-atlas']

# Create lookup dictionaries
ibm_risk_map = {risk.id: risk for risk in ibm_risks}
aiuc1_req_map = {req.id: req for req in aiuc1_requirements}


# Build the crosswalk data 
crosswalk_data = []

for ibm_risk in ibm_risks:
    mapped_aiuc1_reqs = get_mapped_aiuc1_requirements(ibm_risk.id, aiuc1_requirements)
    mapped_reqs_list = []
    for req_id, mapping_types in sorted(mapped_aiuc1_reqs.items()):
        req = aiuc1_req_map.get(req_id)
        if req:
            mapping_str = ', '.join(mapping_types)
            mapped_reqs_list.append(f'{req_id} ({mapping_str})')
    
    crosswalk_data.append({
        'IBM_AI_Risk_Atlas_Risk_ID': ibm_risk.id,
        'IBM_AI_Risk_Atlas_Risk_Name': ibm_risk.name,
        'IBM_Description': ibm_risk.description[:150] if ibm_risk.description else '',
        'Mapped_AIUC1_Requirements_Count': len(mapped_aiuc1_reqs),
        'Mapped_AIUC1_Requirements': ', '.join(mapped_reqs_list) if mapped_reqs_list else ''
    })

crosswalk_df = pd.DataFrame(crosswalk_data)

# Sort by number of mappings (descending)
crosswalk_df = crosswalk_df.sort_values('Mapped_AIUC1_Requirements_Count', ascending=False).reset_index(drop=True)
print("Crosswalk ready")

Crosswalk ready

Now let's understand some stats about the current mapping data.

In [6]:
print('CROSSWALK STATISTICS')
print(f'\nTotal IBM Risks: {len(crosswalk_df)}')
print(f'IBM Risks with AIUC-1 Mappings: {(crosswalk_df["Mapped_AIUC1_Requirements_Count"] > 0).sum()}')
print(f'IBM Risks without Mappings: {(crosswalk_df["Mapped_AIUC1_Requirements_Count"] == 0).sum()}')

print(f'\nMapping Distribution:')
print(f'  Min mappings per risk: {crosswalk_df["Mapped_AIUC1_Requirements_Count"].min()}')
print(f'  Max mappings per risk: {crosswalk_df["Mapped_AIUC1_Requirements_Count"].max()}')
print(f'  Mean mappings per risk: {crosswalk_df["Mapped_AIUC1_Requirements_Count"].mean():.2f}')

print(f'\nTop 10 IBM Risks by AIUC-1 Requirement Count:')
top_risks = crosswalk_df.nlargest(10, 'Mapped_AIUC1_Requirements_Count')[['IBM_AI_Risk_Atlas_Risk_ID', 'IBM_AI_Risk_Atlas_Risk_Name', 'Mapped_AIUC1_Requirements_Count']]
print(top_risks.to_string(index=False))

CROSSWALK STATISTICS

Total IBM Risks: 99

IBM Risks with AIUC-1 Mappings: 77

IBM Risks without Mappings: 22

Mapping Distribution:

  Min mappings per risk: 0

  Max mappings per risk: 6

  Mean mappings per risk: 1.64

Top 10 IBM Risks by AIUC-1 Requirement Count:

              IBM_AI_Risk_Atlas_Risk_ID             IBM_AI_Risk_Atlas_Risk_Name  Mapped_AIUC1_Requirements_Count
           atlas-incorrect-risk-testing                  Incorrect risk testing                                6
                   atlas-harmful-output                          Harmful output                                5
         atlas-unauthorized-use-agentic                        Unauthorized use                                5
             atlas-legal-accountability                    Legal accountability                                5
    atlas-unrepresentative-risk-testing           Unrepresentative risk testing                                4
                   atlas-prompt-leaking                          Prompt leaking                                4
atlas-external-resources-attack-agentic Attack on AI agents' external resources                                3
       atlas-misaligned-actions-agentic                      Misaligned actions                                3
        atlas-lack-of-testing-diversity               Lack of testing diversity                                3
          atlas-harmful-code-generation                 Harmful code generation                                3

Display Crosswalk Table (Mapped Risks only)

In [7]:
# Show only risks with mappings
mapped_risks_df = crosswalk_df[crosswalk_df['Mapped_AIUC1_Requirements_Count'] > 0]
print(f'\nIBM Risks with AIUC-1 Mappings ({len(mapped_risks_df)} risks):')
mapped_risks_df

IBM Risks with AIUC-1 Mappings (77 risks):

,IBM_AI_Risk_Atlas_Risk_ID,IBM_AI_Risk_Atlas_Risk_Name,IBM_Description,Mapped_AIUC1_Requirements_Count,Mapped_AIUC1_Requirements
0,atlas-incorrect-risk-testing,Incorrect risk testing,A metric selected to measure or track a risk i...,6,"aiuc1-req-c001 (Related), aiuc1-req-c002 (Rela..."
1,atlas-harmful-output,Harmful output,A model might generate language that leads to ...,5,"aiuc1-req-c003 (Close), aiuc1-req-c005 (Close)..."
2,atlas-unauthorized-use-agentic,Unauthorized use,Unauthorized use: If attackers can gain access...,5,"aiuc1-req-b006 (Close), aiuc1-req-b007 (Relate..."
3,atlas-legal-accountability,Legal accountability,Determining who is responsible for an AI model...,5,"aiuc1-req-e001 (Related), aiuc1-req-e002 (Rela..."
4,atlas-unrepresentative-risk-testing,Unrepresentative risk testing,Testing is unrepresentative when the test inpu...,4,"aiuc1-req-c001 (Related), aiuc1-req-c002 (Rela..."
...,...,...,...,...,...
72,atlas-impact-human-agency-agentic,AI agents' impact on human agency,The autonomous nature of AI agents in performi...,1,aiuc1-req-c009 (Related)
73,atlas-introduce-data-bias-agentic,Introduce data bias,"Specific actions taken by the AI agent, such a...",1,aiuc1-req-c003 (Related)
74,atlas-untraceable-attribution,Untraceable attribution,The content of the training data used for gene...,1,aiuc1-req-d001 (Related)
75,atlas-non-disclosure,Non-disclosure,Content might not be clearly disclosed as AI g...,1,aiuc1-req-e016 (Close)
76,atlas-data-provenance,Uncertain data provenance,Data provenance refers to the traceability of ...,1,aiuc1-req-e006 (Related)

Understand which risks are not currently mapped.

In [8]:
# Example 1: Find IBM risks without AIUC-1 mappings
unmapped = crosswalk_df[crosswalk_df['Mapped_AIUC1_Requirements_Count'] == 0]
if len(unmapped) > 0:
    print(f"Unmapped risks ({len(unmapped)})")
    print(unmapped[['IBM_AI_Risk_Atlas_Risk_ID', 'IBM_AI_Risk_Atlas_Risk_Name']].to_string(index=False))

Unmapped risks (22)

           IBM_AI_Risk_Atlas_Risk_ID             IBM_AI_Risk_Atlas_Risk_Name
         atlas-unrepresentative-data                   Unrepresentative data
  atlas-impact-human-dignity-agentic                 Impact on human dignity
atlas-discriminatory-actions-agentic                  Discriminatory actions
        atlas-impact-on-human-agency       AI agents' Impact on human agency
           atlas-impact-jobs-agentic               AI agents' impact on jobs
                 atlas-data-curation                  Improper data curation
                  atlas-temporal-gap                            Temporal gap
         atlas-lack-domain-expertise                Lack of domain expertise
                     atlas-exclusion                               Exclusion
    atlas-impact-environment-agentic        AI agents' impact on environment
            atlas-data-contamination                      Data contamination
     atlas-impact-on-the-environment               Impact on the environment
atlas-impact-on-affected-communities          Impact on affected communities
           atlas-improper-retraining                     Improper retraining
            atlas-spreading-toxicity                      Spreading toxicity
    atlas-inaccessible-training-data              Inaccessible training data
                atlas-impact-on-jobs                          Impact on Jobs
            atlas-bypassing-learning Impact on education: bypassing learning
                    atlas-plagiarism         Impact on education: plagiarism
  atlas-impact-on-cultural-diversity            Impact on cultural diversity
             atlas-data-transparency      Lack of training data transparency
                   atlas-overfitting                             Overfitting

## 4. Use Case to Risks to Controls Mapping

This section demonstrates how to take a use case description, identify associated risks from the IBM AI Risk Atlas, and then map those risks to AIUC-1 controls.

In [ ]:
from ai_atlas_nexus.blocks.inference import (

    OllamaInferenceEngine,

)
from ai_atlas_nexus.blocks.inference.params import (
    InferenceEngineCredentials,
 
    OllamaInferenceEngineParams,

)


from typing import List, Dict
import re

def extract_risks_from_usecase(usecase_string: str, ran_instance, inference_engine=None) -> List[Dict]:
    """
    Identify IBM AI Risk Atlas risks 
    
    Args:
        usecase_string: Description of an AI use case
        ran_instance: AIAtlasNexus instance
        inference_engine: inference engine 
    
    Returns:
        List of dictionaries with risk information
    """
    matched_risks = []
    
    # If inference engine is provided, use LLM-based identification
    if inference_engine is not None:
        try:
            risks = ran_instance.identify_risks_from_usecases(
                usecases=[usecase_string],
                inference_engine=inference_engine,
                taxonomy="ibm-risk-atlas",
                max_risk=10,
                zero_shot_only=False
            )
            
            if risks and len(risks) > 0:
                for risk in risks[0]:
                    matched_risks.append({
                        'risk_id': risk.id,
                        'risk_name': risk.name,
                        'risk_description': risk.description[:200] if risk.description else '',
                      
                    
                    })
            
            return matched_risks
        except Exception as e:
            print(f" LLM-based identification failed ({str(e)[:50]}...).")


def get_controls_for_risks(risk_ids: List[str], aiuc1_requirements: List) -> Dict[str, List[Dict]]:
    """
    Get AIUC-1 controls (rules) for a list of IBM risks.
    
    Args:
        risk_ids: List of IBM risk IDs
        aiuc1_requirements: List of AIUC-1 requirement objects
    
    Returns:
        Dictionary mapping risk_id -> list of controls
    """
    risk_to_controls = {}
    #TODO compact this
    for risk_id in risk_ids:
        controls = []
        for req in aiuc1_requirements:
            # Check if risk is in any of the mapping fields
            mapping_fields = ['close_mappings', 'exact_mappings', 'related_mappings', 'broad_mappings', 'narrow_mappings']
            for field_name in mapping_fields:
                if hasattr(req, field_name):
                    field_value = getattr(req, field_name)
                    if field_value and risk_id in (field_value if isinstance(field_value, list) else [field_value]):
                        # Get the control rules for this requirement
                        if hasattr(req, 'hasRule') and req.hasRule:
                            rules = req.hasRule if isinstance(req.hasRule, list) else [req.hasRule]
                            for rule_id in rules:
                                rule = ran.get_by_id(class_name="rules", identifier=rule_id)
                                if rule:
                                    controls.append({
                                        'requirement_id': req.id,
                                        'requirement_name': req.name,
                                        'control_id': rule.id,
                                        'control_name': rule.name if hasattr(rule, 'name') else rule_id,
                                        'control_description': rule.description if hasattr(rule, 'description') else '',
                                        'mapping_type': field_name.replace('_mappings', '')
                                    })
        
        risk_to_controls[risk_id] = controls
    
    return risk_to_controls


def map_usecase_to_controls(usecase_string: str, ran_instance, inference_engine=None, top_k: int = 10) -> pd.DataFrame:
    """
    Map Use case -> IBM Risks -> AIUC-1 Controls
    
    Args:
        usecase_string: Description of an AI use case
        ran_instance: AIAtlasNexus instance
        inference_engine: inference engine
        top_k: Maximum number of top risks to return
    
    Returns:
        DataFrame with use case, risks, and associated AIUC-1 controls
    """

    aiuc1_requirements = ran_instance.get_all(class_name='requirement', taxonomy='aiuc1')
    matched_risks = extract_risks_from_usecase(usecase_string, ran_instance, inference_engine)
    matched_risks = matched_risks[:top_k]  # Keep top K
    
    if not matched_risks:
        return pd.DataFrame()
    
    risk_ids = [r['risk_id'] for r in matched_risks]
    risk_to_controls = get_controls_for_risks(risk_ids, aiuc1_requirements)
    
    results = []
    for risk_info in matched_risks:
        risk_id = risk_info['risk_id']
        controls = risk_to_controls.get(risk_id, [])
        
        if controls:
            for control in controls:
                results.append({
                    'Use_Case': usecase_string[:100],
                    'IBM_Risk_ID': risk_id,
                    'IBM_Risk_Name': risk_info['risk_name'],
                    'Requirement_Mapping_Type': control['mapping_type'],
                    'AIUC1_Requirement_ID': control['requirement_id'],
                    'AIUC1_Requirement_Name': control['requirement_name'],
                    'AIUC1_Control_ID': control['control_id'],
                    'AIUC1_Control_Name': control['control_name'],
                    
                })
        else:
            # Risk with no controls mapped
            results.append({
                'Use_Case': usecase_string[:100],
                'IBM_Risk_ID': risk_id,
                'IBM_Risk_Name': risk_info['risk_name'],
                'Requirement_Mapping_Type': None,
                'AIUC1_Requirement_ID': None,
                'AIUC1_Requirement_Name': None,
                'AIUC1_Control_ID': None,
                'AIUC1_Control_Name': None,
                
            })
    
    return pd.DataFrame(results)


print("Use case mapping functions loaded")

Use case mapping functions loaded (with LLM-based risk identification support)

### 4.1 Example: Financial Chatbot Use Case

Let's demonstrate the use case mapping with a financial chatbot example.

In [10]:
# Example 1: Financial chatbot use case
usecase_1 = """
A financial services company is building a generative AI chatbot to provide 
investment advice to customers. The system uses large language models trained on 
financial data. Key concerns include: preventing hallucinations about market data, 
ensuring data privacy for customer information, securing against prompt injection 
attacks from adversaries, and preventing unauthorized access to sensitive financial records.
The system must maintain audit trails and ensure reliability of tool calls to external systems.
"""


# Option B: Using LLM-based identification (requires inference engine)
inference_engine = OllamaInferenceEngine(
    model_name_or_path="granite3.3:8b",
    credentials=InferenceEngineCredentials(api_url="localhost:11434"),
    parameters=OllamaInferenceEngineParams(
        num_predict=1000, num_ctx=8192, temperature=0, repeat_penalty=1
    )
)


result_df_1 = map_usecase_to_controls(usecase_1, ran, inference_engine=inference_engine)

print(f"\n✓ Identified {result_df_1['IBM_Risk_ID'].nunique()} risks and {len(result_df_1)} control mappings")
print(f"\nTop risks identified:")
print(result_df_1[['IBM_Risk_ID', 'IBM_Risk_Name']].drop_duplicates('IBM_Risk_ID').head(10).to_string(index=False))

print(f"\n\nFull mapping results:")
result_df_1

[2026-02-26 10:49:27:518] - INFO - AIAtlasNexus - OLLAMA inference engine will execute requests on the server at localhost:11434.
[2026-02-26 10:49:27:572] - INFO - AIAtlasNexus - Created OLLAMA inference engine.
Inferring with OLLAMA: 100%|██████████| 1/1 [00:21<00:00, 21.81s/it]

✓ Identified 8 risks and 54 control mappings

Top risks identified:

                         IBM_Risk_ID                 IBM_Risk_Name
   atlas-membership-inference-attack   Membership inference attack
   atlas-confidential-data-in-prompt   Confidential data in prompt
                atlas-prompt-leaking                Prompt leaking
           atlas-data-privacy-rights Data privacy rights alignment
                 atlas-hallucination                 Hallucination
atlas-exploit-trust-mismatch-agentic        Exploit trust mismatch
         atlas-unrepresentative-data         Unrepresentative data
              atlas-prompt-injection       Prompt injection attack

Full mapping results:

,Use_Case,IBM_Risk_ID,IBM_Risk_Name,Requirement_Mapping_Type,AIUC1_Requirement_ID,AIUC1_Requirement_Name,AIUC1_Control_ID,AIUC1_Control_Name
0,\nA financial services company is building a g...,atlas-membership-inference-attack,Membership inference attack,related,aiuc1-req-a005,Prevent cross-customer data exposure,aiuc1-ctrl-a005-1,A005.1 Documentation: Consent for combined dat...
1,\nA financial services company is building a g...,atlas-membership-inference-attack,Membership inference attack,related,aiuc1-req-a005,Prevent cross-customer data exposure,aiuc1-ctrl-a005-2,A005.2 Config: Customer data isolation controls
2,\nA financial services company is building a g...,atlas-membership-inference-attack,Membership inference attack,related,aiuc1-req-a005,Prevent cross-customer data exposure,aiuc1-ctrl-a005-3,A005.3 Config: Privacy-enhancing controls
3,\nA financial services company is building a g...,atlas-membership-inference-attack,Membership inference attack,related,aiuc1-req-b004,Prevent AI endpoint scraping,aiuc1-ctrl-b004-1,B004.1 Config: Anomalous usage detection
4,\nA financial services company is building a g...,atlas-membership-inference-attack,Membership inference attack,related,aiuc1-req-b004,Prevent AI endpoint scraping,aiuc1-ctrl-b004-2,B004.2 Config: Rate limits
5,\nA financial services company is building a g...,atlas-membership-inference-attack,Membership inference attack,related,aiuc1-req-b004,Prevent AI endpoint scraping,aiuc1-ctrl-b004-3,B004.3 Report: External pentest of AI endpoints
6,\nA financial services company is building a g...,atlas-membership-inference-attack,Membership inference attack,related,aiuc1-req-b004,Prevent AI endpoint scraping,aiuc1-ctrl-b004-4,B004.4 Documentation: Vulnerability remediation
7,\nA financial services company is building a g...,atlas-confidential-data-in-prompt,Confidential data in prompt,close,aiuc1-req-a004,Protect IP and trade secrets,aiuc1-ctrl-a004-1,A004.1 Documentation: User guidance on confide...
8,\nA financial services company is building a g...,atlas-confidential-data-in-prompt,Confidential data in prompt,close,aiuc1-req-a004,Protect IP and trade secrets,aiuc1-ctrl-a004-2,A004.2 Documentation: foundational model IP pr...
9,\nA financial services company is building a g...,atlas-confidential-data-in-prompt,Confidential data in prompt,close,aiuc1-req-a004,Protect IP and trade secrets,aiuc1-ctrl-a004-3,A004.3 Config: IP detection implementation
10,\nA financial services company is building a g...,atlas-confidential-data-in-prompt,Confidential data in prompt,close,aiuc1-req-a004,Protect IP and trade secrets,aiuc1-ctrl-a004-4,A004.4 Config: IP disclosure monitoring
11,\nA financial services company is building a g...,atlas-confidential-data-in-prompt,Confidential data in prompt,related,aiuc1-req-a004,Protect IP and trade secrets,aiuc1-ctrl-a004-1,A004.1 Documentation: User guidance on confide...
12,\nA financial services company is building a g...,atlas-confidential-data-in-prompt,Confidential data in prompt,related,aiuc1-req-a004,Protect IP and trade secrets,aiuc1-ctrl-a004-2,A004.2 Documentation: foundational model IP pr...
13,\nA financial services company is building a g...,atlas-confidential-data-in-prompt,Confidential data in prompt,related,aiuc1-req-a004,Protect IP and trade secrets,aiuc1-ctrl-a004-3,A004.3 Config: IP detection implementation
14,\nA financial services company is building a g...,atlas-confidential-data-in-prompt,Confidential data in prompt,related,aiuc1-req-a004,Protect IP and trade secrets,aiuc1-ctrl-a004-4,A004.4 Config: IP disclosure monitoring
15,\nA financial services company is building a g...,atlas-confidential-data-in-prompt,Confidential data in prompt,related,aiuc1-req-a006,Prevent PII leakage,aiuc1-ctrl-a006-1,A006.1 Config: PII detection and filtering
16,\nA financial services company is building a g...,atlas-confidential-data-in-prompt,Confidential data in prompt,related,aiuc1-req-a006,Prevent PII leakage,aiuc1-ctrl-a006-2,A006.2 Config: PII access controls
17,\nA financial services company is building a g...,atlas-confidential-data-in-prompt,Confidential data in prompt,related,aiuc1-req-a006,Prevent PII leakage,aiuc1-ctrl-a006-3,A006.3 Config: DLP system integration
18,\nA financial services company is building a g...,atlas-prompt-leaking,Prompt leaking,related,aiuc1-req-a004,Protect IP and trade secrets,aiuc1-ctrl-a004-1,A004.1 Documentation: User guidance on confide...
19,\nA financial services company is building a g...,atlas-prompt-leaking,Prompt leaking,related,aiuc1-req-a004,Protect IP and trade secrets,aiuc1-ctrl-a004-2,A004.2 Documentation: foundational model IP pr...
20,\nA financial services company is building a g...,atlas-prompt-leaking,Prompt leaking,related,aiuc1-req-a004,Protect IP and trade secrets,aiuc1-ctrl-a004-3,A004.3 Config: IP detection implementation
21,\nA financial services company is building a g...,atlas-prompt-leaking,Prompt leaking,related,aiuc1-req-a004,Protect IP and trade secrets,aiuc1-ctrl-a004-4,A004.4 Config: IP disclosure monitoring
22,\nA financial services company is building a g...,atlas-prompt-leaking,Prompt leaking,related,aiuc1-req-b003,Manage public release of technical details,aiuc1-ctrl-b003-1,B003.1 Documentation: Technical information di...
23,\nA financial services company is building a g...,atlas-prompt-leaking,Prompt leaking,related,aiuc1-req-b003,Manage public release of technical details,aiuc1-ctrl-b003-2,B003.2 Documentation: Public disclosure approv...
24,\nA financial services company is building a g...,atlas-prompt-leaking,Prompt leaking,related,aiuc1-req-b004,Prevent AI endpoint scraping,aiuc1-ctrl-b004-1,B004.1 Config: Anomalous usage detection
25,\nA financial services company is building a g...,atlas-prompt-leaking,Prompt leaking,related,aiuc1-req-b004,Prevent AI endpoint scraping,aiuc1-ctrl-b004-2,B004.2 Config: Rate limits
26,\nA financial services company is building a g...,atlas-prompt-leaking,Prompt leaking,related,aiuc1-req-b004,Prevent AI endpoint scraping,aiuc1-ctrl-b004-3,B004.3 Report: External pentest of AI endpoints
27,\nA financial services company is building a g...,atlas-prompt-leaking,Prompt leaking,related,aiuc1-req-b004,Prevent AI endpoint scraping,aiuc1-ctrl-b004-4,B004.4 Documentation: Vulnerability remediation
28,\nA financial services company is building a g...,atlas-prompt-leaking,Prompt leaking,related,aiuc1-req-b009,Limit output over-exposure,aiuc1-ctrl-b009-1,B009.1 Config: Output volume limits
29,\nA financial services company is building a g...,atlas-prompt-leaking,Prompt leaking,related,aiuc1-req-b009,Limit output over-exposure,aiuc1-ctrl-b009-2,B009.2 Demonstration: User output notices
30,\nA financial services company is building a g...,atlas-prompt-leaking,Prompt leaking,related,aiuc1-req-b009,Limit output over-exposure,aiuc1-ctrl-b009-3,B009.3 Config: Output precision controls
31,\nA financial services company is building a g...,atlas-data-privacy-rights,Data privacy rights alignment,related,aiuc1-req-a001,Establish input data policy,aiuc1-ctrl-a001-1,A001.1 Documentation: Policy for input data ow...
32,\nA financial services company is building a g...,atlas-data-privacy-rights,Data privacy rights alignment,related,aiuc1-req-a001,Establish input data policy,aiuc1-ctrl-a001-2,A001.2 Config: Data retention implementation
33,\nA financial services company is building a g...,atlas-data-privacy-rights,Data privacy rights alignment,related,aiuc1-req-a001,Establish input data policy,aiuc1-ctrl-a001-3,A001.3 Documentation: Data subject right proce...
34,\nA financial services company is building a g...,atlas-data-privacy-rights,Data privacy rights alignment,related,aiuc1-req-a002,Establish output data policy,aiuc1-ctrl-a002-1,A002.1 Documentation: Output usage and ownersh...
35,\nA financial services company is building a g...,atlas-data-privacy-rights,Data privacy rights alignment,related,aiuc1-req-e012,Document regulatory compliance,aiuc1-ctrl-e012-1,E012.1 Documentation: Regulatory compliance re...
36,\nA financial services company is building a g...,atlas-hallucination,Hallucination,close,aiuc1-req-d001,Prevent hallucinated outputs,aiuc1-ctrl-d001-1,D001.1 Config: Groundedness filter
37,\nA financial services company is building a g...,atlas-hallucination,Hallucination,close,aiuc1-req-d001,Prevent hallucinated outputs,aiuc1-ctrl-d001-2,D001.2 Demonstration: User-facing citations & ...
38,\nA financial services company is building a g...,atlas-hallucination,Hallucination,close,aiuc1-req-d001,Prevent hallucinated outputs,aiuc1-ctrl-d001-3,D001.3 Demonstration: User-facing uncertainty ...
39,\nA financial services company is building a g...,atlas-hallucination,Hallucination,close,aiuc1-req-d002,Third-party testing for hallucinations,aiuc1-ctrl-d002-1,D002.1 Report: Hallucination testing results
40,\nA financial services company is building a g...,atlas-hallucination,Hallucination,close,aiuc1-req-e003,AI failure plan for hallucinations,aiuc1-ctrl-e003-1,E003.1 Documentation: AI failure plan for hall...
41,\nA financial services company is building a g...,atlas-hallucination,Hallucination,close,aiuc1-req-e003,AI failure plan for hallucinations,aiuc1-ctrl-e003-2,E003.2 Documentation: Additional hallucination...
42,\nA financial services company is building a g...,atlas-exploit-trust-mismatch-agentic,Exploit trust mismatch,related,aiuc1-req-b006,Prevent unauthorized AI agent actions,aiuc1-ctrl-b006-1,B006.1 Config: Agent service access restrictions
43,\nA financial services company is building a g...,atlas-exploit-trust-mismatch-agentic,Exploit trust mismatch,related,aiuc1-req-b006,Prevent unauthorized AI agent actions,aiuc1-ctrl-b006-2,B006.2 Config: Agent security monitoring and a...
44,\nA financial services company is building a g...,atlas-exploit-trust-mismatch-agentic,Exploit trust mismatch,related,aiuc1-req-b007,Enforce user access privileges to AI systems,aiuc1-ctrl-b007-1,B007.1 Config: User access controls
45,\nA financial services company is building a g...,atlas-exploit-trust-mismatch-agentic,Exploit trust mismatch,related,aiuc1-req-b007,Enforce user access privileges to AI systems,aiuc1-ctrl-b007-2,B007.2 Documentation: Access reviews
46,\nA financial services company is building a g...,atlas-unrepresentative-data,Unrepresentative data,NaN,NaN,NaN,NaN,NaN
47,\nA financial services company is building a g...,atlas-prompt-injection,Prompt injection attack,close,aiuc1-req-b001,Third-party testing of adversarial robustness,aiuc1-ctrl-b001-1,B001.1 Report: adversarial testing results
48,\nA financial services company is building a g...,atlas-prompt-injection,Prompt injection attack,close,aiuc1-req-b001,Third-party testing of adversarial robustness,aiuc1-ctrl-b001-2,B001.2 Documentation: Security program integra...
49,\nA financial services company is building a g...,atlas-prompt-injection,Prompt injection attack,close,aiuc1-req-b002,Detect adversarial input,aiuc1-ctrl-b002-1,B002.1 Config: Adversarial input detection and...
50,\nA financial services company is building a g...,atlas-prompt-injection,Prompt injection attack,close,aiuc1-req-b002,Detect adversarial input,aiuc1-ctrl-b002-2,B002.2 Logs: Adversarial incident and response
51,\nA financial services company is building a g...,atlas-prompt-injection,Prompt injection attack,close,aiuc1-req-b002,Detect adversarial input,aiuc1-ctrl-b002-3,B002.3 Documentation: Updates to detection config
52,\nA financial services company is building a g...,atlas-prompt-injection,Prompt injection attack,close,aiuc1-req-b002,Detect adversarial input,aiuc1-ctrl-b002-4,B002.4 Config: Pre-processing adversarial dete...
53,\nA financial services company is building a g...,atlas-prompt-injection,Prompt injection attack,close,aiuc1-req-b002,Detect adversarial input,aiuc1-ctrl-b002-5,B002.5 Config: AI security alerts

### 4.2 Example: HR Recruitment AI System

In [11]:
# Example 2: HR recruitment AI system
usecase_2 = """
An HR department deploys an AI system to screen and rank job applicants. The system 
analyzes resumes and application materials to identify the best candidates. Key risks: 
the model may exhibit bias in screening decisions based on demographic information, 
leading to discriminatory outcomes. There is also risk of unrepresentative testing data, 
data quality issues, and concerns about transparency and accountability. The system 
could produce incorrect risk testing in candidate assessment.
"""

# Using keyword-based matching
result_df_2 = map_usecase_to_controls(usecase_2, ran, inference_engine=inference_engine)

print(f"\n✓ Identified {result_df_2['IBM_Risk_ID'].nunique()} risks and {len(result_df_2)} control mappings")
print(f"\nTop risks identified:")
print(result_df_2[['IBM_Risk_ID', 'IBM_Risk_Name']].drop_duplicates('IBM_Risk_ID').head(10).to_string(index=False))

print(f"\n\nFull mapping results:")
result_df_2

Inferring with OLLAMA: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it]

✓ Identified 10 risks and 63 control mappings

Top risks identified:

                         IBM_Risk_ID                  IBM_Risk_Name
        atlas-incorrect-risk-testing         Incorrect risk testing
        atlas-over-or-under-reliance        Over- or under-reliance
atlas-discriminatory-actions-agentic         Discriminatory actions
    atlas-lack-of-model-transparency     Lack of model transparency
         atlas-unrepresentative-data          Unrepresentative data
     atlas-lack-of-testing-diversity      Lack of testing diversity
                     atlas-data-bias                      Data bias
             atlas-data-usage-rights Data usage rights restrictions
      atlas-unauthorized-use-agentic               Unauthorized use
     atlas-lack-of-data-transparency      Lack of data transparency

Full mapping results:

,Use_Case,IBM_Risk_ID,IBM_Risk_Name,Requirement_Mapping_Type,AIUC1_Requirement_ID,AIUC1_Requirement_Name,AIUC1_Control_ID,AIUC1_Control_Name
0,\nAn HR department deploys an AI system to scr...,atlas-incorrect-risk-testing,Incorrect risk testing,related,aiuc1-req-c001,Define AI risk taxonomy,aiuc1-ctrl-c001-1,C001.1 Documentation: AI risk taxonomy
1,\nAn HR department deploys an AI system to scr...,atlas-incorrect-risk-testing,Incorrect risk testing,related,aiuc1-req-c001,Define AI risk taxonomy,aiuc1-ctrl-c001-2,C001.2 Documentation: Risk taxonomy reviews
2,\nAn HR department deploys an AI system to scr...,atlas-incorrect-risk-testing,Incorrect risk testing,related,aiuc1-req-c002,Conduct pre-deployment testing,aiuc1-ctrl-c002-1,C002.1 Documentation: Pre-deployment test and ...
3,\nAn HR department deploys an AI system to scr...,atlas-incorrect-risk-testing,Incorrect risk testing,related,aiuc1-req-c002,Conduct pre-deployment testing,aiuc1-ctrl-c002-2,C002.2 Config: SDLC integration
4,\nAn HR department deploys an AI system to scr...,atlas-incorrect-risk-testing,Incorrect risk testing,related,aiuc1-req-c002,Conduct pre-deployment testing,aiuc1-ctrl-c002-3,C002.3 Documentation: Vulnerability scan results
...,...,...,...,...,...,...,...,...
58,\nAn HR department deploys an AI system to scr...,atlas-lack-of-data-transparency,Lack of data transparency,related,aiuc1-req-a001,Establish input data policy,aiuc1-ctrl-a001-2,A001.2 Config: Data retention implementation
59,\nAn HR department deploys an AI system to scr...,atlas-lack-of-data-transparency,Lack of data transparency,related,aiuc1-req-a001,Establish input data policy,aiuc1-ctrl-a001-3,A001.3 Documentation: Data subject right proce...
60,\nAn HR department deploys an AI system to scr...,atlas-lack-of-data-transparency,Lack of data transparency,related,aiuc1-req-e017,Document system transparency policy,aiuc1-ctrl-e017-1,E017.1 Documentation: Transparency policy
61,\nAn HR department deploys an AI system to scr...,atlas-lack-of-data-transparency,Lack of data transparency,related,aiuc1-req-e017,Document system transparency policy,aiuc1-ctrl-e017-2,E017.2 Documentation: Model cards and system d...
62,\nAn HR department deploys an AI system to scr...,atlas-lack-of-data-transparency,Lack of data transparency,related,aiuc1-req-e017,Document system transparency policy,aiuc1-ctrl-e017-3,E017.3 Documentation: Transparency report shar...

### 4.3 Using Your Own Use Case

The `map_usecase_to_controls()` function can be applied to any AI system use case.

In [12]:
# Template: Replace with your own use case
my_usecase = """
[Describe your AI agent here:
- What is the agent's purpose?
- What are the key concerns and risks?
- What data does it process?
- What decisions does it make?
- Who does it impact?
]
"""

# Uncomment and run to analyze your use case
# result_df = map_usecase_to_controls(my_usecase, ran, inference_engine=inference_engine)
# print(f"Identified {len(result_df)} control mappings from {result_df['IBM_Risk_ID'].nunique()} risks")
# result_df

### 4.4 Analyzing Results

In [13]:
def summarize_usecase_analysis(result_df: pd.DataFrame) -> Dict:
    """
    Generate a summary 
    
    Args:
        result_df: DataFrame returned by map_usecase_to_controls()
    
    Returns:
        Dictionary with summary statistics
    """
    if result_df.empty:
        return {"status": "No risks identified"}
    
    summary = {
        "total_risks_identified": result_df['IBM_Risk_ID'].nunique(),
        "total_controls_mapped": len(result_df),
        "risks_with_no_controls": (result_df['AIUC1_Control_ID'].isna()).sum(),
        "risks_with_controls": (result_df['AIUC1_Control_ID'].notna()).sum(),
        "unique_requirements": result_df['AIUC1_Requirement_ID'].nunique(),
        "mapping_types": result_df['Mapping_Type'].value_counts().to_dict() if 'Mapping_Type' in result_df.columns else {},
        "top_5_risks": result_df[['IBM_Risk_ID', 'IBM_Risk_Name']].drop_duplicates('IBM_Risk_ID').head(5).values.tolist()
    }
    return summary


# Analyze financial chatbot results

print("FINANCIAL CHATBOT USE CASE - SUMMARY")

summary_1 = summarize_usecase_analysis(result_df_1)
for key, value in summary_1.items():
    if key != 'top_5_risks':
        print(f"{key}: {value}")
print("\nTop 5 Identified Risks:")
for i, (risk_id, risk_name) in enumerate(summary_1['top_5_risks'], 1):
    print(f"  {i}. {risk_id}: {risk_name}")


print("HR RECRUITMENT SYSTEM USE CASE - SUMMARY")

summary_2 = summarize_usecase_analysis(result_df_2)
for key, value in summary_2.items():
    if key != 'top_5_risks':
        print(f"{key}: {value}")
print("\nTop 5 Identified Risks:")
for i, (risk_id, risk_name) in enumerate(summary_2['top_5_risks'], 1):
    print(f"  {i}. {risk_id}: {risk_name}")

FINANCIAL CHATBOT USE CASE - SUMMARY

total_risks_identified: 8

total_controls_mapped: 54

risks_with_no_controls: 1

risks_with_controls: 53

unique_requirements: 16

mapping_types: {}

Top 5 Identified Risks:

  1. atlas-membership-inference-attack: Membership inference attack

  2. atlas-confidential-data-in-prompt: Confidential data in prompt

  3. atlas-prompt-leaking: Prompt leaking

  4. atlas-data-privacy-rights: Data privacy rights alignment

  5. atlas-hallucination: Hallucination

HR RECRUITMENT SYSTEM USE CASE - SUMMARY

total_risks_identified: 10

total_controls_mapped: 63

risks_with_no_controls: 2

risks_with_controls: 61

unique_requirements: 18

mapping_types: {}

Top 5 Identified Risks:

  1. atlas-incorrect-risk-testing: Incorrect risk testing

  2. atlas-over-or-under-reliance: Over- or under-reliance

  3. atlas-discriminatory-actions-agentic: Discriminatory actions

  4. atlas-lack-of-model-transparency: Lack of model transparency

  5. atlas-unrepresentative-data: Unrepresentative data

## 5. Sunburst Chart Visualizations

Visualize the hierarchical relationships between use cases, risks, requirements, and controls using sunburst charts.

In [14]:
import plotly.graph_objects as go
from collections import defaultdict

### 5.1 Financial Chatbot Use Case - Hierarchical Visualization

In [15]:
# check the data quality
print("Financial Chatbot Data Quality Check:")
print(f"Total rows: {len(result_df_1)}")
print(f"Rows with IBM_Risk_ID: {result_df_1['IBM_Risk_ID'].notna().sum()}")
print(f"Rows with AIUC1_Requirement_ID: {result_df_1['AIUC1_Requirement_ID'].notna().sum()}")
print(f"Rows with AIUC1_Control_ID: {result_df_1['AIUC1_Control_ID'].notna().sum()}")
print(f"Complete rows (all three fields): {result_df_1.dropna(subset=['IBM_Risk_ID', 'AIUC1_Requirement_ID', 'AIUC1_Control_ID']).shape[0]}")

print("Sample of data:")
print(result_df_1[['IBM_Risk_ID', 'AIUC1_Requirement_ID', 'AIUC1_Control_ID']].head(10))

Financial Chatbot Data Quality Check:

Total rows: 54

Rows with IBM_Risk_ID: 54

Rows with AIUC1_Requirement_ID: 53

Rows with AIUC1_Control_ID: 53

Complete rows (all three fields): 53

Sample of data:

                         IBM_Risk_ID AIUC1_Requirement_ID   AIUC1_Control_ID
0  atlas-membership-inference-attack       aiuc1-req-a005  aiuc1-ctrl-a005-1
1  atlas-membership-inference-attack       aiuc1-req-a005  aiuc1-ctrl-a005-2
2  atlas-membership-inference-attack       aiuc1-req-a005  aiuc1-ctrl-a005-3
3  atlas-membership-inference-attack       aiuc1-req-b004  aiuc1-ctrl-b004-1
4  atlas-membership-inference-attack       aiuc1-req-b004  aiuc1-ctrl-b004-2
5  atlas-membership-inference-attack       aiuc1-req-b004  aiuc1-ctrl-b004-3
6  atlas-membership-inference-attack       aiuc1-req-b004  aiuc1-ctrl-b004-4
7  atlas-confidential-data-in-prompt       aiuc1-req-a004  aiuc1-ctrl-a004-1
8  atlas-confidential-data-in-prompt       aiuc1-req-a004  aiuc1-ctrl-a004-2
9  atlas-confidential-data-in-prompt       aiuc1-req-a004  aiuc1-ctrl-a004-3

In [16]:
import plotly.express as px
# sunburst 
px_fig = px.sunburst(result_df_1, 
                     path=['IBM_Risk_ID', 'AIUC1_Requirement_ID', 'AIUC1_Control_ID'], 
                     title="Financial Services AI Chatbot: Risks → Requirements → Controls")

px_fig.show()
# treemap 
fig = px.treemap(result_df_1, 
                 path=['IBM_Risk_ID', 'AIUC1_Requirement_ID', 'AIUC1_Control_ID'], 
                hover_data=['IBM_Risk_Name']
                )
fig.show()

**Layers:**
- **Layer 1 (inner ring):** Identified IBM AI Risk Atlas risks
- **Layer 2 (middle ring):** Mapped AIUC-1 requirements addressing those risks
- **Layer 3 (outer ring):** Specific control activities that implement the requirements

### 5.2 HR Recruitment AI System - Hierarchical Visualization

In [17]:
# Data quality check for HR recruitment
print("HR Recruitment AI Data Quality Check:")
print(f"Total rows: {len(result_df_2)}")
print(f"Rows with IBM_Risk_ID: {result_df_2['IBM_Risk_ID'].notna().sum()}")
print(f"Rows with AIUC1_Requirement_ID: {result_df_2['AIUC1_Requirement_ID'].notna().sum()}")
print(f"Rows with AIUC1_Control_ID: {result_df_2['AIUC1_Control_ID'].notna().sum()}")
print(f"Complete rows (all three fields): {result_df_2.dropna(subset=['IBM_Risk_ID', 'AIUC1_Requirement_ID', 'AIUC1_Control_ID']).shape[0]}")
print()

HR Recruitment AI Data Quality Check:

Total rows: 63

Rows with IBM_Risk_ID: 63

Rows with AIUC1_Requirement_ID: 61

Rows with AIUC1_Control_ID: 61

Complete rows (all three fields): 61

In [18]:
#  HR recruitment use case
import plotly.express as px
# sunburst 
px_fig_2 = px.sunburst(result_df_2, 
                     path=['IBM_Risk_ID', 'AIUC1_Requirement_ID', 'AIUC1_Control_ID'], 
                     title="HR Recruitment AI System: Risks → Requirements → Controls")

px_fig_2.show()
# treemap 
fig_2 = px.treemap(result_df_2, 
                 path=['IBM_Risk_ID', 'AIUC1_Requirement_ID', 'AIUC1_Control_ID'], 
                hover_data=['IBM_Risk_Name']
                )
fig_2.show()

The HR recruitment system shows a different risk profile compared to the financial chatbot, with emphasis on fairness, bias, and testing-related risks.

In [19]:
print("Summary for both use cases:")
print("=" * 70)

for idx, (result_df, name) in enumerate([(result_df_1, "Financial Chatbot"), (result_df_2, "HR Recruitment AI")], 1):
    unique_risks = result_df['IBM_Risk_ID'].nunique()
    unique_reqs = result_df['AIUC1_Requirement_ID'].nunique()
    unique_controls = result_df['AIUC1_Control_ID'].nunique()
    
    print(f"\n{idx}. {name}")
    print(f"   Identified Risks: {unique_risks}")
    print(f"   AIUC-1 Requirements: {unique_reqs}")
    print(f"   AIUC-1 Controls: {unique_controls}")
    print(f"   Total Control Mappings: {len(result_df)}")

Summary for both use cases:

======================================================================

1. Financial Chatbot

   Identified Risks: 8

   AIUC-1 Requirements: 16

   AIUC-1 Controls: 41

   Total Control Mappings: 54

2. HR Recruitment AI

   Identified Risks: 10

   AIUC-1 Requirements: 18

   AIUC-1 Controls: 49

   Total Control Mappings: 63